# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('preview_image', models.FileField(upload_to='')),
                ('download_link', models.CharField(max_length=200)),
                ('copyright_title', models.CharField(max_length=50, verbose_name='copyright title link')),
                ('copyright_link', models.CharField(max_length=200, verbose_name='copy right link address')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CATEGORIES')),
            ],
        ),
    ]
