# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='views',
        ),
    ]
